project_id = "jioakguorsfvjuzyclrg"

[functions.auth-vk-start]
verify_jwt = false

[functions.auth-vk-callback]
verify_jwt = false

[functions.auth-telegram-start]
verify_jwt = false

[functions.auth-telegram-callback]
verify_jwt = false
